test_profile:
  outputs:
    dev:
      dataset: dataset
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: credentials.json
      location: US
      method: service-account
      priority: interactive
      project: project
      threads: 1
      type: bigquery
  target: dev